---
php_ver: 5
php_fpm:
  - php{{ php_ver }}-fpm
php_cli:
  - php{{ php_ver }}-cli
php_ext:
  - php{{ php_ver }}-curl
  - php{{ php_ver }}-gd
  - php{{ php_ver }}-mysql
  - php{{ php_ver }}-imagick
php_fpm_pool: /etc/php5/fpm/pool.d
php_fpm_service: php5-fpm
php_fpm_sock_pfx: /run/shm


