---
- name: Load distro specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Install nginx
  package: name=nginx state=present

- name: Copy files
  copy: src={{ item }} dest=/etc/nginx/conf.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - client_max_body_size.conf
    - hide_server_tokens.conf
    - ssl.conf
  notify: reload nginx

- name: Enable nginx
  service: name=nginx enabled=yes state=started

- name: Allow nginx to access home
  acl: path={{ getent_passwd[user_name][4] }} state=present etype={{ item.etype }} permissions={{ item.permissions }} entity={{ item.entity }}
  with_items:
    - { etype: user,  permissions: r-x, entity: "{{ nginx_user }}" }
