---
- name: Install php-fpm
  package: name={{ item }} state=present
  with_items:
    - php{{ php_ver }}-fpm
    - php{{ php_ver }}-curl
    - php{{ php_ver }}-gd
    - php{{ php_ver }}-mysql
    - php{{ php_ver }}-json
    - "{{ php_imagick }}"
    - "{{ php_mbstring }}"
    - "{{ php_xml }}"
  when: item != ""

- name: Install pool file
  template: src=pool.conf.j2 dest={{ php_etc_base }}/fpm/pool.d/{{ user_name }}.conf owner=root group=root mode=0644
  notify: restart fpm

- name: Enable php-fpm
  service: name=php{{ php_ver }}-fpm enabled=yes state=started
