---
- name: Load distro specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Install MySQL
  package: name={{ item }} state=present
  with_items:
    - "{{ mysql_client }}"
    - "{{ mysql_server }}"
    - "{{ mysql_pyconn }}"

- name: Enable MySQL
  service: name={{ mysql_svc }} enabled=yes state=started

- name: Create database
  mysql_db: config_file=/etc/mysql/debian.cnf name={{ mysql_db }} state=present

- name: Create mysql user
  mysql_user: config_file=/etc/mysql/debian.cnf name={{ mysql_user }} password={{ mysql_pass }} state=present priv="{{ mysql_db }}.*:ALL"
