---
- name: Ensure jessie-backports repo is present
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    state: present

- name: Install certbot
  apt: name=certbot state=latest default_release=jessie-backports
