---
- name: Install ca-certificates package
  apt: name=ca-certificates state=latest

- name: Add CertBot PPA
  apt_repository: repo='ppa:certbot/certbot' update_cache=yes

- name: Install certbot
  apt: name=certbot state=latest
