---
- name: Install ca-certificates package
  apt: name=ca-certificates state=latest

- name: Add CertBot PPA
  apt_repository: repo='ppa:certbot/certbot' update_cache=yes
  when: (ansible_distribution_major_version < "17") or (ansible_distribution_release == "zesty")

- name: Install certbot
  apt: name=certbot state=latest
