---
- set_fact:
    ssh_svc: sshd
    cacheable: true
  when: ansible_distribution == "CentOS"

- set_fact:
    ssh_svc: ssh
    cacheable: true
  when: ansible_distribution != "CentOS"

- name: Install OpenSSH server
  package: name=openssh-server state=present

- name: Set up SFTP
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match Group sftponly
          ForceCommand internal-sftp
          ChrootDirectory /%h
    backup: yes
  notify: reload ssh

- name: Make sure SSH is enabled
  service: name={{ ssh_svc }} enabled=yes state=started
