---
- name: Load distro specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"
    - "{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: Install php
  package: name={{ item }} state=present
  with_items:
    - "{{ php_fpm }}"
    - "{{ php_cli }}"
    - "{{ php_ext }}"

- name: Install pool file
  template: src=pool.conf.j2 dest={{ php_fpm_pool }}/{{ user_name }}.conf owner=root group=root mode=0644
  notify: restart fpm

- name: Enable php-fpm
  service: name={{ php_fpm_service }} enabled=yes state=started
