---
- set_fact:
    php_ver: 5
    php_fpm_pool: /etc/php5/fpm/pool.d
    php_imagick: php5-imagick
    php_mbstring: ""
    php_xml: ""
    php_fpm_sock_pfx: /run/shm
    cacheable: true
  when: (ansible_distribution == "Debian") and (ansible_distribution_major_version <= "8")

- set_fact:
    php_ver: ""
    php_fpm_pool: /etc/php-fpm.d
    php_imagick: ""
    php_mbstring: php-mbstring
    php_xml: php-xml
    php_fpm_sock_pfx: /run/php-fpm
    cacheable: true
  when: (ansible_distribution == "CentOS")

- set_fact:
    php_ver: 7.1
    php_fpm_pool: /etc/php/7.1/fpm/pool.d
    php_imagick: php-imagick
    php_mbstring: php7.1-mbstring
    php_xml: php7.1-xml
    php_fpm_sock_pfx: /run/shm
    cacheable: true
  when: (ansible_distribution == "Ubuntu") and ((ansible_distribution_major_version > "17") or (ansible_distribution_release == "artful"))

- set_fact:
    php_ver: 7.0
    php_fpm_pool: /etc/php/7.0/fpm/pool.d
    php_imagick: php-imagick
    php_mbstring: php7.0-mbstring
    php_xml: php7.0-xml
    php_fpm_sock_pfx: /run/shm
    cacheable: true
  when: php_ver is not defined
